### ISSUE TITLE
Feature template successfully imported but not device template

### ISSUE THREAD

**Issue by fcbob** [CiscoSE/cisco-sd-wan-export-import#1]
After running script, I could easily import/export feature template from one vManage to another but received following error for device template. 

device_template
Device template: Importing Factory_Default_C1111_8PLTELA_V01 - Failed to create device template - Template is a factory default
Traceback (most recent call last):
  File "sd-wan-exim.py", line 1562, in <module>
    configure(SDWAN_CONFIG)
  File "sd-wan-exim.py", line 1458, in configure
    import_device_templates(file_path, all_template_ids, all_policy_ids)
  File "sd-wan-exim.py", line 864, in import_device_templates
    response = sdwanp.post_request(mount_point, item)
  File "sd-wan-exim.py", line 173, in post_request
    raise CiscoException("Fail - Post")
__main__.CiscoException: Fail - Post

Can you please have a look and advise accordingly

**Comment by fkuris** [comment]
I have the same problem.

**Comment by centenod** [comment]
I have similar issue:

Device template: Importing Factory_Default_ISR_4331_V01 - Failed to create device template - Template is a factory default

**Comment by ws360** [comment]
Sastre from Cisco does an excellent job
